const SUPABASE_URL='https://cqhsvhbfeuaujmkiyuzh.supabase.co';
const SUPABASE_KEY='sb_publishable_fGdgSsziZzeNiMBMT6S_AA_WO0FaLuY';
const sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let cases=[];
let demoMode=false;
const $=id=>document.getElementById(id);
const yen=n=>'¥'+Math.round(Number(n||0)).toLocaleString('ja-JP');
const net=c=>Number(c.amount||0)*(1-Number(c.fee_rate||0)/100);
const escapeHtml=(s='')=>String(s).replace(/[&<>'\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','\"':'&quot;'}[m]));
function showAuth(){$('authView').classList.remove('hidden');$('appView').classList.add('hidden')}
function showApp(){$('authView').classList.add('hidden');$('appView').classList.remove('hidden')}
async function init(){const {data}=await sb.auth.getSession();if(data.session?.user){showApp();await loadCases()}else showAuth()}
async function signIn(){$('authMsg').textContent='ログイン中…';const {error}=await sb.auth.signInWithPassword({email:$('authEmail').value.trim(),password:$('authPassword').value});if(error){$('authMsg').textContent=error.message;return}$('authMsg').textContent='';demoMode=false;$('appSub').textContent='クラウド案件管理';showApp();await loadCases()}
async function signUp(){$('authMsg').textContent='アカウント作成中…';const {data,error}=await sb.auth.signUp({email:$('authEmail').value.trim(),password:$('authPassword').value});if(error){$('authMsg').textContent=error.message;return}if(data.session){demoMode=false;showApp();await loadCases()}else $('authMsg').textContent='確認メールを確認後、ログインしてください。'}
function openDemo(){demoMode=true;$('appSub').textContent='デモ表示（サンプルデータ・保存なし）';$('newBtn').style.display='none';$('refreshBtn').style.display='none';$('logoutBtn').textContent='デモ終了';cases=[
{id:'demo1',customer:'Aさん',title:'定型Excel作業の自動化相談',status:'要件整理',case_type:'3,000円相談',amount:3000,fee_rate:22,due_date:'2026-08-29',last_contact_date:'2026-08-25',next_action:'現行ファイルと作業手順を確認',memo:'毎日30分かかる集計作業を自動化したい',coconala_url:''},
{id:'demo2',customer:'Bさん',title:'画像整理ツール制作',status:'開発中',case_type:'本制作',amount:15000,fee_rate:22,due_date:'2026-09-03',last_contact_date:'2026-08-24',next_action:'ドラッグ＆ドロップ処理を実装',memo:'Windows向けの軽量ツール',coconala_url:''},
{id:'demo3',customer:'Cさん',title:'API連携の実現可否相談',status:'見積提示',case_type:'3,000円相談',amount:3000,fee_rate:22,due_date:'2026-08-31',last_contact_date:'2026-08-25',next_action:'見積回答待ち',memo:'外部サービス連携の可否調査',coconala_url:''},
{id:'demo4',customer:'Dさん',title:'月次レポート自動生成',status:'納品待ち',case_type:'本制作',amount:22000,fee_rate:22,due_date:'2026-08-27',last_contact_date:'2026-08-25',next_action:'最終確認後に納品',memo:'Excel出力とPDF生成',coconala_url:''}
];showApp();render()}
async function logout(){if(demoMode){demoMode=false;cases=[];$('newBtn').style.display='';$('refreshBtn').style.display='';$('logoutBtn').textContent='ログアウト';$('appSub').textContent='クラウド案件管理';showAuth();return}await sb.auth.signOut();cases=[];showAuth()}
async function loadCases(){if(demoMode){render();return}$('caseList').innerHTML='<div class="empty">読み込み中…</div>';const {data,error}=await sb.from('cases').select('*').order('created_at',{ascending:false});if(error){$('caseList').innerHTML='<div class="empty">読み込み失敗: '+escapeHtml(error.message)+'</div>';return}cases=data||[];render()}
function render(){const st=$('filterStatus').value;const q=$('search').value.trim().toLowerCase();const list=cases.filter(c=>(!st||c.status===st)&&(!q||(`${c.customer} ${c.title}`).toLowerCase().includes(q)));$('caseList').innerHTML='';if(!list.length)$('caseList').innerHTML='<div class="empty">案件はまだありません。</div>';else list.forEach(c=>{const d=document.createElement('article');d.className='case';d.innerHTML=`<div><h3>${escapeHtml(c.title)}</h3><div class="meta"><span>${escapeHtml(c.customer)}</span><span class="badge">${escapeHtml(c.status)}</span><span>${escapeHtml(c.case_type)}</span>${c.due_date?`<span>納期 ${escapeHtml(c.due_date)}</span>`:''}</div><div class="next">${c.next_action?'次：'+escapeHtml(c.next_action):'次のアクション未設定'}</div></div><div class="money"><b>${yen(c.amount)}</b><small>手取り ${yen(net(c))}</small><br><button data-id="${c.id}" class="editBtn">開く</button></div>`;$('caseList').appendChild(d)});const active=cases.filter(c=>c.status!=='完了');$('kActive').textContent=active.length;$('kConsult').textContent=active.filter(c=>c.case_type==='3,000円相談').length;$('kSales').textContent=yen(active.reduce((s,c)=>s+Number(c.amount||0),0));$('kNet').textContent=yen(active.reduce((s,c)=>s+net(c),0));document.querySelectorAll('.editBtn').forEach(b=>b.onclick=()=>openEdit(b.dataset.id))}
function openNew(){if(demoMode)return alert('デモでは保存できません');$('caseForm').reset();$('caseId').value='';$('status').value='相談受付';$('caseType').value='3,000円相談';$('amount').value=3000;$('feeRate').value=22;$('deleteBtn').classList.add('hidden');$('modalTitle').textContent='新規案件';$('modal').classList.add('open')}
function openEdit(id){const c=cases.find(x=>x.id===id);if(!c)return;$('caseId').value=c.id;$('customer').value=c.customer||'';$('title').value=c.title||'';$('status').value=c.status||'相談受付';$('caseType').value=c.case_type||'3,000円相談';$('amount').value=c.amount||0;$('feeRate').value=c.fee_rate??22;$('dueDate').value=c.due_date||'';$('lastContactDate').value=c.last_contact_date||'';$('nextAction').value=c.next_action||'';$('memo').value=c.memo||'';$('coconalaUrl').value=c.coconala_url||'';$('deleteBtn').classList.toggle('hidden',demoMode);$('modalTitle').textContent=demoMode?'案件詳細（デモ）':'案件編集';$('modal').classList.add('open')}
function closeModal(){$('modal').classList.remove('open')}
async function saveCase(e){e.preventDefault();if(demoMode)return alert('デモでは保存できません');const payload={customer:$('customer').value.trim(),title:$('title').value.trim(),status:$('status').value,case_type:$('caseType').value,amount:Number($('amount').value||0),fee_rate:Number($('feeRate').value||0),due_date:$('dueDate').value||null,last_contact_date:$('lastContactDate').value||null,next_action:$('nextAction').value.trim()||null,memo:$('memo').value.trim()||null,coconala_url:$('coconalaUrl').value.trim()||null};if(!payload.customer||!payload.title)return alert('顧客名と案件名は必須です');const result=$('caseId').value?await sb.from('cases').update(payload).eq('id',$('caseId').value):await sb.from('cases').insert(payload);if(result.error)return alert('保存失敗: '+result.error.message);closeModal();await loadCases()}
async function removeCase(){if(demoMode)return;if(!$('caseId').value||!confirm('この案件を削除しますか？'))return;const {error}=await sb.from('cases').delete().eq('id',$('caseId').value);if(error)return alert('削除失敗: '+error.message);closeModal();await loadCases()}
$('signInBtn').onclick=signIn;$('signUpBtn').onclick=signUp;$('demoBtn').onclick=openDemo;$('logoutBtn').onclick=logout;$('refreshBtn').onclick=loadCases;$('newBtn').onclick=openNew;$('closeBtn').onclick=closeModal;$('cancelBtn').onclick=closeModal;$('deleteBtn').onclick=removeCase;$('caseForm').onsubmit=saveCase;$('filterStatus').onchange=render;$('search').oninput=render;$('modal').onclick=e=>{if(e.target===$('modal'))closeModal()};if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=3').catch(()=>{});init();